version: '3'
services:
  proxnut:
    build:
      context: ./proxnut-proxy
      dockerfile: Dockerfile
    ports:
        - "3003:3003"
    environment:
      - PROXY_HOST=proxnut
      - BACKEND_HOST=backend
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  backend:
    build:
      context: ./demo-backend
      dockerfile: Dockerfile
    ports:
        - "4444:4444"

  frontend:
    build:
      context: ./frontend/cashu-wallet-wc
      dockerfile: Dockerfile
    ports:
        - "8080:80"
  demo:
    build:
      context: ./demo-frontend
      dockerfile: Dockerfile
    ports:
        - "5173:5173"
  redis:
    command: redis-server --appendonly yes
    image: redis
    ports:
        - "6379:6379"
    volumes:
        - ./redis-volume:/data
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
        - "5515:5515"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      